services:
    dbsync-remote:
        image: bitnami/java:17-debian-11
        command: /home/eip/install.sh
        container_name: dbsync-remote
        network_mode: host
        env_file:
            - ./eip.env
        working_dir: /home/eip
        volumes: 
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ./install.sh:/home/eip/install.sh
            - ./:/home/openmrs-eip-docker
            - ./shared:/home/eip/shared
        restart: unless-stopped
