export DB_HOST="172.17.0.1"
export DB_HOST_PORT="$openmrs_db_port"
export DB_USER="root"
export DB_PASSWD="$spring_openmrs_datasource_password"
export DB_NAME="openmrs_eip_sender_mgt_${db_sync_senderId}"
