#!/bin/sh
# This scrip is intended to generate notification content which can be picked-up by send notification tool
#

#ENV
HOME_DIR="/home/eip"
SCRIPTS_DIR="$HOME_DIR/scripts"
LOG_DIR="$HOME_DIR/shared/logs/notification"
CRONS_DIR="$HOME_DIR/cron"
NOTIFICATION_HOME="$HOME_DIR/shared/notifications"

MAIL_RECIPIENTS=$1
MAIL_SUBJECT=$2
EMAIL_CONTENT_FILE=$3
EMAIL_ATTACHMENT=$4

FILE_NAME=$(basename "$EMAIL_ATTACHMENT")

. $SCRIPTS_DIR/commons.sh
. $SCRIPTS_DIR/try_to_load_environment.sh

timestamp=$(getCurrDateTime)

CURR_NOTIFICATION_FOLDER="${NOTIFICATION_HOME}/${FILE_NAME}_${timestamp}"

LOG_FILE="$LOG_DIR/notifications.log"

echo "MAIL_RECIPIENTS: $MAIL_RECIPIENTS"
echo "MAIL_SUBJECT: $MAIL_SUBJECT"
echo "EMAIL_CONTENT_FILE: $(basename $EMAIL_CONTENT_FILE)"
echo "EMAIL_ATTACHMENT: $(basename $EMAIL_ATTACHMENT)"
echo "CURR_NOTIFICATION_FOLDER: $CURR_NOTIFICATION_FOLDER"

mkdir -p $CURR_NOTIFICATION_FOLDER

echo $MAIL_RECIPIENTS > $CURR_NOTIFICATION_FOLDER/MAIL_RECIPIENTS
echo $MAIL_SUBJECT > $CURR_NOTIFICATION_FOLDER/MAIL_SUBJECT
mv $EMAIL_CONTENT_FILE $CURR_NOTIFICATION_FOLDER/EMAIL_CONTENT_FILE
mv $EMAIL_ATTACHMENT $CURR_NOTIFICATION_FOLDER/EMAIL_ATTACHMENT

echo "Ready" > $CURR_NOTIFICATION_FOLDER/ready

logToScreenAndFile "Notification stuff generated for $CURR_NOTIFICATION_FOLDER at $timestamp" "$LOG_FILE"
